### PR TITLE
Write test for RenderList component

### PR DESCRIPTION
**Pull request by souzasmatheus**

### CODE REVIEW

**Comment by atherdon** [comment]
@souzasmatheus tell me if you'll need help with it

**Comment by souzasmatheus** [comment]
@atherdon , I am not so sure of how I am supposed to write those tests. Is the last commit getting any closer to what you expect?
Thank you!

**Comment by atherdon** [comment]
Not a problem - this is why i'm teaching you ;) don't worry - this problems is part of learning curve. will review your commit right now

**Comment by atherdon** [comment]
it still crash our build, because you didn't include Enzyme adapter to this file.
So it's actually one line - that prevent me to merge your changes

**Comment by atherdon** [comment]
@souzasmatheus should i help you with this issue? just want to merge your changes and move to the next task with you

**Comment by souzasmatheus** [comment]
@atherdon I am sorry. I misunderstood your last message. I will correct the last commit.

**Comment by atherdon** [comment]
and add a configuration for the adapter

**Comment by souzasmatheus** [comment]
@atherdon I wonder if I have to update the package.json file

**Comment by atherdon** [comment]
tell me more what do you mean.

**Comment by atherdon** [comment]
we have a new issue, here a details: https://travis-ci.org/GroceriStar/pdf-export-component/jobs/492225659

**Comment by souzasmatheus** [comment]
Wouldn't  I have to add a line like 
```
"jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/path/to/your/file.js",
 }
```
to the package.json file?

**Comment by atherdon** [comment]
i don't think it's necessary. our testing config works out of the box.
and it stored here: https://github.com/GroceriStar/pdf-export-component/blob/master/jest.config.js

this issue related to just names. if you review code at src folder deeply - you may find your issue quickly ;)

**Comment by atherdon** [comment]
check this new error. you actually can run yarn test before commit - in order to see does your tests works https://travis-ci.org/GroceriStar/pdf-export-component/jobs/492241663

**Pull request merged**
