### PR TITLE
Separate each RenderList by folder

### PR DESCRIPTION
**Pull request by souzasmatheus**

### CODE REVIEW

**Comment by atherdon** [comment]
as i also make some updates at our master branch you'll need to sync your fork with master branch.
Do you know how to do it?

**Comment by souzasmatheus** [comment]
I'd have to fetch your master branch into a new branch in my directory, then I would merge this new branch into my master branch and then push it into my fork, right?

**Comment by atherdon** [comment]
in short yes, but if you'll have problems, check this videos:
https://github.com/ChickenKyiv/awesome-git-article/blob/master/README.md#forking-pull-requests

and buzz me if you'll have problems

**Comment by souzasmatheus** [comment]
I believe I was able to make a pull request succesfully.

**Comment by atherdon** [comment]
Looks fine, small note - did you update paths at *test.js file?

**Comment by atherdon** [comment]
i mean this file: https://github.com/souzasmatheus/pdf-export-component/blob/master/src/components/RenderLists/RenderList.test.js

**Comment by souzasmatheus** [comment]
Ops, I forgot that one. I apologize. I will correct that, ok?

**Comment by atherdon** [comment]
not a problem at all, this is my job to review changes.
sure, please fix it

**Comment by atherdon** [comment]
Plus please update paths at index.js file

**Comment by atherdon** [comment]
looks fine, merging

**Pull request merged**
